spring:
  application:
    name: Service-2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/service2?useSSL=false&serverTimezone=UTC'
    username: 'root'
    password: 'admin'
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    schemas: service2
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org:
      hibernate: error