server:
  port: 8081

logging:
  level:
    org:
      hibernate: error

spring:
  application:
    name: CustomerService

  datasource:
    ## You often do not need to specify the driver-class-name,
    ## since Spring Boot can deduce it for most databases from the url.
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/customer_service?useSSL=false&serverTimezone=UTC'
    username: 'root'
    password: 'root'
    platform: mysql
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000

  jpa:
    show-sql: true
    open-in-view: false
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate

  flyway:
    #Enable or disable flyway migrations
    enabled: true
    url: 'jdbc:mysql://localhost:3306/mysql'
    schemas: customer_service
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}